# Generated by Django 3.0.5 on 2020-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
                ('precio', models.FloatField()),
                ('telefono', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('imageA', models.ImageField(upload_to='post_images')),
                ('imageB', models.ImageField(upload_to='post_images')),
                ('imageC', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
