# Generated by Django 3.0.5 on 2020-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carSales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ciudad',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageC',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
